import uuid
from typing import Annotated

from fastapi import APIRouter, HTTPException, Query, status
from openai import OpenAIError
from pydantic import BaseModel

from app.core.dependencies import CurrentUserIdDep, DatabaseDep
from app.integrations import ai as ai_integration
from app.models.enums import CEFRLevel, SourceType
from app.repositories.content import ContentRepository
from app.repositories.content_question import ContentQuestionRepository
from app.schemas.content import ContentListResponse, ContentResponse, InteractRequest
from app.schemas.errors import RESPONSES_401, RESPONSES_404, RESPONSES_422
from app.services.content import ContentService

router = APIRouter()


def _service(db: DatabaseDep) -> ContentService:
    return ContentService(ContentRepository(db))


@router.get(
    "",
    response_model=ContentListResponse,
    responses={**RESPONSES_401, **RESPONSES_422},
)
async def list_content(
    db: DatabaseDep,
    user_id: CurrentUserIdDep,
    language: str | None = None,
    cefr_level: CEFRLevel | None = None,
    source_type: SourceType | None = None,
    page: Annotated[int, Query(ge=1, le=100_000)] = 1,
    page_size: Annotated[int, Query(ge=1, le=100)] = 20,
) -> ContentListResponse:
    return await _service(db).list(
        language=language,
        cefr_level=cefr_level,
        source_type=source_type,
        page=page,
        page_size=page_size,
    )


@router.get(
    "/{content_id}",
    response_model=ContentResponse,
    responses={**RESPONSES_401, **RESPONSES_404, **RESPONSES_422},
)
async def get_content(
    content_id: uuid.UUID,
    db: DatabaseDep,
    user_id: CurrentUserIdDep,
) -> ContentResponse:
    return await _service(db).get_by_id(content_id)


@router.post(
    "/{content_id}/interact",
    status_code=status.HTTP_204_NO_CONTENT,
    responses={**RESPONSES_401, **RESPONSES_404, **RESPONSES_422},
)
async def interact_with_content(
    content_id: uuid.UUID,
    data: InteractRequest,
    db: DatabaseDep,
    user_id: CurrentUserIdDep,
) -> None:
    await _service(db).interact(
        user_id=user_id,
        content_id=content_id,
        data=data,
    )


class QuestionResponse(BaseModel):
    id: uuid.UUID
    question: str
    options: list[str]
    answer_index: int

    model_config = {"from_attributes": True}


@router.get(
    "/{content_id}/questions",
    response_model=list[QuestionResponse],
    responses={
        **RESPONSES_401,
        **RESPONSES_404,
        503: {"description": "AI service unavailable"},
    },
)
async def get_or_generate_questions(
    content_id: uuid.UUID,
    db: DatabaseDep,
    user_id: CurrentUserIdDep,
    n: Annotated[int, Query(ge=1, le=10)] = 5,
) -> list[QuestionResponse]:
    """Return comprehension questions for a content item.

    Questions are generated by AI on first request and cached.  Subsequent
    calls return the cached questions instantly without calling the AI again.
    Pass ``?n=<1-10>`` to control how many questions are generated (only
    respected on the first call; ignored once questions are cached).
    """
    content = await _service(db).get_by_id(content_id)

    q_repo = ContentQuestionRepository(db)
    cached = await q_repo.get_by_content_id(content_id)
    if cached:
        return [QuestionResponse.model_validate(q) for q in cached]

    try:
        raw_questions = await ai_integration.generate_questions(
            content_title=content.title,
            content_description=content.description or "",
            language=content.language,
            n=n,
        )
    except RuntimeError as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(exc),
        ) from exc
    except OpenAIError as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="AI service unavailable — please try again later.",
        ) from exc

    if not raw_questions:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="AI returned no questions — please try again later.",
        )

    saved = await q_repo.create_bulk(content_id, raw_questions)
    return [QuestionResponse.model_validate(q) for q in saved]
